<?php

    class group extends YDDatabaseObject {
    
        function group() {

            $this->YDDatabaseObject();

            $this->registerDatabase( $GLOBALS['YDDBOBJ_CONN'] );
            $this->registerTable( 'groups' );
            
            // Fields
            $this->registerKey( 'id', true );
            $this->registerField( 'name' );
            $this->registerField( 'active' );
            
            // Relations
            $rel = & $this->registerRelation( 'user', true, 'user', 'user_group' );
            $rel->setCrossLocalKey( 'group_id' );
            $rel->setCrossForeignKey( 'user_id' );
            
            // Callbacks
            $this->registerCallback( 'debug', 'insert' );
            $this->registerCallback( 'debug', 'delete' );
            $this->registerCallback( 'debug', 'delete', true );
            $this->registerCallback( 'debug', 'update', true );
            // $this->unregisterCallback( 'debug' ); // unregister from all actions
            $this->unregisterCallback( 'debug', 'insert' ); // unregister from action "insert"
            
        }
        
        function debug( $action, $before ) {
            
            YDDebugUtil::debug( 'This was generated by the callback "debug" ' . ( $before ? 'before' : 'after' ) .  ' action "' . $action . '" was executed.' );
            
        }
        
    }


?>